### ISSUE TITLE
[TASK] Move survey and rules logic from models to services

### ISSUE THREAD

**Issue by shurwit** [rokwire/app-flutter-plugin#232]
**Is your feature request related to a problem? Please describe.**
Currently we contain a lot of logic in methods within the `Survey` and `RulesEngine` models. This logic should be abstracted out and moved into various service to keep the models/dependencies simple.

**Describe the solution you'd like**
We should move all non-accessor logic out of the Survey (and related) model and into the Surveys service. We should also create a Rules service and move all non-accessor logic from of the RulesEnginer (and related) model.

**Comment by roberlander2** [comment]
This will be addressed in #263.
